POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### check if user is blocked

POST http://localhost:8000/users/isblocked
Content-Type: application/json

{
  "email": "admin@admin.com"
}