# Use an official Node.js runtime as the base image
FROM node:18

ARG DB_USERNAME=root
ARG DB_PASSWORD=teste
ARG DB_DATABASE=mer
ARG DB_HOST=localhost

ARG MQ_HOST=localhost
ARG MQ_USER=guest
ARG MQ_PASS=guest

#COPY ./src /merApi

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .
COPY yarn.lock .

RUN npm install --global nodemon
RUN npm install

# Copy the rest of the application code
# COPY . .

# Expose the port the API is listening on
EXPOSE 8000

# Start the API server with nodemon for development
CMD [ "npm", "run", "dev" ]
