version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - rabbitmq
    env_file:
    - .env
  db:
    image: postgres
    env_file:
    - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
  wave2image:
    image: merteam/wave2image:latest
    env_file:
    - .env
    environment:
      - HOST=rabbitmq 
      - USER=${MQ_USER}
      - PASS=${MQ_PASS}
      - PORT=${MQ_PORT}
      - MNG_PORT=${MQ_MNG_PORT}
      - TIME=10
    volumes:
      - audios:/Audios
      - soundwaves:/Soundwaves
    depends_on:
      rabbitmq:
        condition: service_healthy
  vidextractor:
    image: merteam/vidextractor:latest
    env_file:
    - .env
    environment:
      - HOST=rabbitmq 
      - USER=${MQ_USER}
      - PASS=${MQ_PASS}
      - PORT=${MQ_PORT}
      - MNG_PORT=${MQ_MNG_PORT}
      - TIME=10
    volumes:
      - audios:/Audios
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres-data:
  audios:
  soundwaves: