# Use a smaller base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .
COPY yarn.lock .

# Install Yarn globally
RUN npm install --global yarn

# Install dependencies
RUN yarn install --production

# Copy the source code
COPY . .

# Expose the port your app runs on
EXPOSE 8000

# Start your app
CMD ["yarn", "start"]
