version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - rabbitmq
    env_file:
    - .env
  db:
    image: postgres
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
    - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
  dummy-manager:
    build:
      context: ./dummy-manager
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
  dummy-worker:
    build:
      context: ./dummy-worker
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      dummy-manager:
      rabbitmq:
        condition: service_healthy
      
volumes:
  postgres-data: