version: '3.8'

services:
  # this extends the base docker-compose.yml, att: the paths here are relative to project root
  api:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.devcontainer
    volumes:
      - .:/workspaces/mermaid-api:cached
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.

