ARG VARIANT="20-buster"
FROM mcr.microsoft.com/devcontainers/javascript-node:1-${VARIANT}

# Install Hadolint
RUN curl -Lo /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 && \
    chmod +x /usr/local/bin/hadolint